#include "smiles.h"

const char *smiles[] = {
    [1] ":D",
    [2] ":))",
    [3] ":DD",
    [4] ";)",
    [5] "8)",
    [6] ":)",
    [7] ":|",
    [8] ":/",
    [9] ":o",
    [10] ":(",
    [11] ">:(",
    [12] ":'(",
    [13] "*andel/dabel*",
    [14] "*smoking*",
    [15] "*srdce*",
    [16] "*kytka*",
    [17] ":{",
    [18] "=)",
    [19] "*skaredy_pohled*",
    [20] ":.)",
    [21] "*mimo*",
    [22] "*pivo*",
    [23] ":-x",
//    [24] "", // fialovej toci ocima
    [25] "*zamilovane_oci*",
    [26] "*mmnt*",
    [27] "*amor*",
    [28] "*zarofka*",
    [29] "*hodiny*",
//    [30] "", // rve a krici
    [31] "*slunicko*",
    [32] "*oblizovak*",
    [33] "*telefon*",
    [34] "*paranoidni*",
    [35] "*kafe*",
//    [36] "", // toci ocima
    [37] ":-E",
    [38] "*zmotanej_xicht*",
    [39] ">E",
    [40] "*zubatej*",
    [43] "8",
    [45] ":-*",
    [47] ":DD",
    [53] "*chrrr*",
    [54] "*stopa*",
    [55] "*vozickar*",
    [59] "*ziiv*",
    [61] "*kocka*",
    [64] "*pichacka*",
    [70] ":P",
    [71] "*omg*",
    [77] "*rit*",
    [87] "*mava*",
    [88] "*oboci*",
    [90] "*!*",
//     [92] "", // toci ocima a plazi jazyk
    [99] "*zelva_ninja*",
    [102] "*bum*"
};

const int smiles_count = sizeof(smiles)/sizeof(*smiles);
